<?php
/**
 *
 */

/**
 * Implements hook_block_info().
 */
function stark_banner_block_info() {
  // This example comes from node.module.
  $blocks['banner'] = array(
    'info' => t('Stark Banner'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function stark_banner_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'banner':
      $items = array();
      $block['subject'] = t('Stark Banner');
      $block['content'] = array(
        '#theme' => 'stark_banner',
        '#title' => t('Stark Banner'),
        '#items' => $items
      );
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function stark_banner_theme($existing, $type, $theme, $path) {
  return array(
    'stark_banner' => array(
      'variables' => array('items' => null, 'title' => null),
      'template' => 'stark-banner'
    ),
    'stark_banner_item' => array(
      'variables' => array('image' => null, 'title' => null, 'text' => null, 'position' => null),
      'template' => 'stark-banner-item'
    )
  );
}
